name: Dependency example 4 jobs

on:
  push:
    branches: [ BranchePull ]

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Job 1
              run: echo "Job 1"

    job2:
        needs: job1
        runs-on: ubuntu-latest
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v8
              with:
                name: Test.txt
                path: ./Downloads

    job3:
        needs: job1
        runs-on: ubuntu-latest
        steps:
            - name: Job 3
              run: echo "Job 3"

    job4:
        needs: job3
        runs-on: ubuntu-latest
        steps:
            - name: Job 4
              run: echo "Job 4"