name: Workflow Toto

on:
  schedule:
  - cron: '*/5 * * * *'
  - cron: '0 * * * *'
  pull_request:
    types: [opened, reopened]
    branches: [ master, BranchePull ]

jobs:
    hello_world:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Hello world action step
              run: |
                echo "Hello, world!"
                ls -lah
            - name: step 2
              run: echo "Hello, world!"

    hello_world2:
        runs-on: ubuntu-latest
        steps:
            - name: Hello world action step
              run: |
                echo "Hello, world2!"
                ls -lah